### ISSUE TITLE
Community Update Launcher Doesn't Detect Renderers

### ISSUE THREAD

**Issue by Kezyma** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#24]
Just installed on a Steam copy of Deus Ex on Windows 11.
I've tried both of the launcher options in the installer and both times, no renderers show up in the available list when launching through Steam or Deus Ex Community Update.exe
However, if I run Kentie's DeusExe.exe from the same location, the renderer list is populated.

I could be missing something obvious as I've not set up Deus Ex in years.

**Comment by Defaultplayer001** [comment]
Thanks so much for the report! You're absolutely right, I missed this due to a mistake I made when messing with .int stuff that writes an incomplete .ini file which messes up the renderer detection. It only effects you if you didn't have a pre-existing .ini, which I did from previous testing.

It's what I get for not doing a completely clean test trying to rush it out before I had to leave for work lol.

My bad, I'll have a fix out shortly! 

If you use Kentie's anyways though you'll be fine, that uses a non-local ini by default so it won't suffer the same issue.

**Comment by Defaultplayer001** [comment]
Did you delete your old install before reinstalling?

**Comment by Kezyma** [comment]
I've just deleted the game and re-installed it through Steam and I've found I'm still having the same issue! Will look and see if there are perhaps some config files elsewhere that I need to clear too

**Comment by Kezyma** [comment]
Can confirm now that to resolve this, you need to delete the Documents\DeusEx\System directory on top of uninstalling the game! Seems that steam was happy to leave it in place and it had the broken file! 

Not sure how to contact the person who emailed, or if this will get to them, but doing that should resolve it.
