### ISSUE TITLE
No subtitles and no HUD/GUI in 3.0

### ISSUE THREAD

**Issue by RaymanMago1265** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#29]
I finally tested the 3.0 version and well this launch is a little mess, firts of all the game doesn't change to my langauge (spanish, i know the steamy library don't count) and i need to do this manually, and second the game don't show GUI/HUD after starting new game, even the subtitles in the intro doesn't show,

**Comment by Defaultplayer001** [comment]
Thanks so much for submitting the issue! 

I looked into it, and the language setting issue was due to me forgetting it when I switched to a root based install and started using DeusEx.ini by default. I accounted for that in the language set and it works now! 

As for the UI, I just accidently shipped the Steam Library User.ini as the default, whoops! 
![ehe-anime](https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update-/assets/21971271/a73ad39f-c30c-44f4-b8eb-4946d697af6e)

Will release an update containing the fixes shortly, sorry for the trouble and thanks again!
