### ISSUE TITLE
Main menu is black, can't use it properly

### ISSUE THREAD

**Issue by Mabadman** [Defaultplayer001/Deus-Ex-Universe-Community-Update-#35]
Talked about in [this Reddit thread](https://old.reddit.com/r/Deusex/comments/1d1vknj/dx1_help_with_community_update_24_cant_see_game/l5x5rya/?context=5), I experienced myself too.

![g01pxp4bxz2d1](https://github.com/user-attachments/assets/bd4d2fb3-c303-41c3-a216-482a1a63e62b)

According to linked comment, this is due to MenuThemeName and HUDThemeName being set to "COPS" instead of "Cops"

**Comment by Mabadman** [comment]
Oh, the linked comment is by Defaultplayer001, oops. I guess he's aware of the issue.

The wrong color is still a problem though.

**Comment by Defaultplayer001** [comment]
Issue on older versions, thought i fixed it in 3.3 but if there's still an edge case just make sure your userini has the following lines:
MenuThemeName=Cops
HUDThemeName=Cops
 in that Exact case and with no spaces at the end
oh also make sure your installing on a fresh DX copy

Will def be fixed in 3.4!
